//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatClient.ChatServerReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChatServerReference.IChatServer")]
    public interface IChatServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatServer/LogIn", ReplyAction="http://tempuri.org/IChatServer/LogInResponse")]
        string LogIn(string callBackUrl, string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatServer/SendMessage", ReplyAction="http://tempuri.org/IChatServer/SendMessageResponse")]
        string SendMessage(string token, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatServer/LogOut", ReplyAction="http://tempuri.org/IChatServer/LogOutResponse")]
        string LogOut(string token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatServerChannel : ChatServerReference.IChatServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatServerClient : System.ServiceModel.ClientBase<ChatServerReference.IChatServer>, ChatServerReference.IChatServer
    {
        
        public ChatServerClient() {
        }
        
        public ChatServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChatServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChatServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChatServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string LogIn(string callBackUrl, string user, string password) {
            return base.Channel.LogIn(callBackUrl, user, password);
        }
        
        public string SendMessage(string token, string message) {
            return base.Channel.SendMessage(token, message);
        }
        
        public string LogOut(string token) {
            return base.Channel.LogOut(token);
        }
    }
}
